package org.jprotocol.example.handler;
import org.jprotocol.framework.dsl.*;
import org.jprotocol.framework.handler.*;
import org.jprotocol.example.api.*;
/**
* This class is generated by DefaultHandlerGenerator.groovy
* @author eliasa01
*/
abstract public class AbstractMyLeafProtocolAHandler extends Handler<MyLeafProtocolA_Request_API, MyLeafProtocolA_Response_API> {
    protected AbstractMyLeafProtocolAHandler(Type type, boolean msbFirst, String upperHeaderRequestFieldName, int lowerHeaderRequestValue, int lowerHeaderResponseValue, IProtocolState protocolState, IProtocolSniffer sniffer) {
        super(new org.jprotocol.example.dsl.MyLeafProtocolA(), type, msbFirst, upperHeaderRequestFieldName, lowerHeaderRequestValue, lowerHeaderResponseValue, protocolState, sniffer);
    }
    @Override public final MyLeafProtocolA_Request_API createRequest(IProtocolMessage p) {
        return new MyLeafProtocolA_Request_API(p);
    }
    @Override public final MyLeafProtocolA_Response_API createResponse(IProtocolMessage p) {
        return new MyLeafProtocolA_Response_API(p);
    }
}
