package org.jprotocol.example.handler;
import org.jprotocol.framework.dsl.*;
import org.jprotocol.framework.handler.*;
import org.jprotocol.example.api.*;
/**
* This class is generated by DefaultHandlerGenerator.groovy
* @author eliasa01
*/
abstract public class AbstractMyMiddleProtocolBHandler extends Handler<MyMiddleProtocolB_Request_API, MyMiddleProtocolB_Response_API> {
    protected AbstractMyMiddleProtocolBHandler(Type type, boolean msbFirst, String headerFieldName, int headerReceiveValue, int headerSendValue, IProtocolState protocolState, IProtocolSniffer sniffer) {
        super(new org.jprotocol.example.dsl.MyMiddleProtocolB(), type, msbFirst, headerFieldName, headerReceiveValue, headerSendValue, protocolState, sniffer);
    }
    @Override public final MyMiddleProtocolB_Request_API createRequest(IProtocolMessage p) {
        return new MyMiddleProtocolB_Request_API(p);
    }
    @Override public final MyMiddleProtocolB_Response_API createResponse(IProtocolMessage p) {
        return new MyMiddleProtocolB_Response_API(p);
    }
}
