package org.jprotocol.example.handler;
import org.jprotocol.framework.dsl.*;
import org.jprotocol.framework.handler.*;
import org.jprotocol.example.api.*;
/**
* This class is generated by DefaultHandlerGenerator.groovy
* @author eliasa01
*/
abstract public class AbstractMyLeafProtocolBHandler extends Handler<MyLeafProtocolB_Request_API, MyLeafProtocolB_Response_API> {
    protected AbstractMyLeafProtocolBHandler(Type type, boolean msbFirst, String headerFieldName, int headerReceiveValue, int headerSendValue, IProtocolState protocolState, IProtocolSniffer sniffer) {
        super(new org.jprotocol.example.dsl.MyLeafProtocolB(), type, msbFirst, headerFieldName, headerReceiveValue, headerSendValue, protocolState, sniffer);
    }
    @Override public final MyLeafProtocolB_Request_API createRequest(IProtocolMessage p) {
        return new MyLeafProtocolB_Request_API(p);
    }
    @Override public final MyLeafProtocolB_Response_API createResponse(IProtocolMessage p) {
        return new MyLeafProtocolB_Response_API(p);
    }
}
