package org.jprotocol.example.handler;
import org.jprotocol.framework.dsl.*;
import org.jprotocol.framework.handler.*;
import org.jprotocol.example.api.*;
/**
* This class is generated by DefaultHandlerGenerator.groovy
* @author eliasa01
*/
public class DefaultMyMiddleProtocolAHandler extends Handler<MyMiddleProtocolA_Request_API, MyMiddleProtocolA_Response_API> {
    protected DefaultMyMiddleProtocolAHandler(Type type, boolean msbFirst, String upperHeaderRequestFieldName, String upperHeaderResponseFieldName, int lowerHeaderRequestValue, int lowerHeaderResponseValue, IProtocolState protocolState, IProtocolSniffer sniffer) {
        super(new org.jprotocol.example.dsl.MyMiddleProtocolA(), type, msbFirst, upperHeaderRequestFieldName, upperHeaderResponseFieldName, lowerHeaderRequestValue, lowerHeaderResponseValue, protocolState, sniffer);
    }
    @Override public final MyMiddleProtocolA_Request_API createRequest(IProtocolMessage p) {
        return new MyMiddleProtocolA_Request_API(p);
    }
    @Override public final MyMiddleProtocolA_Response_API createResponse(IProtocolMessage p) {
        return new MyMiddleProtocolA_Response_API(p);
    }
}
