package org.jprotocol.example.api;
import org.jprotocol.framework.api.*;
import org.jprotocol.framework.dsl.*;
import org.jprotocol.quantity.Quantity;
import java.util.Iterator;
import org.jprotocol.framework.test.ITestable;
/**
* MyLeafProtocolB Request
* @note This class is generated by DefaultAPIGenerator.groovy
*/
@SuppressWarnings("all")
public class MyLeafProtocolB_Request_API extends AbstractDecoratedProtocolMessage {
    public static final String NAME = "MyLeafProtocolB Request";
    private final MyLeafProtocolB_Request_API parent;
    public MyLeafProtocolB_Request_API(IProtocolLayoutType type) {
        this(new ProtocolMessage(type, false));
    }
    public MyLeafProtocolB_Request_API(IProtocolMessage protocol) {
        this(protocol, false);
    }
    private MyLeafProtocolB_Request_API(IProtocolMessage protocol, boolean strBuilder) {
        super(protocol, strBuilder);
        this.parent = this;
    }
    static MyLeafProtocolB_Request_API_Test createTest(StringBuilderProtocolMessage protocol) {
        return new MyLeafProtocolB_Request_API_Test(protocol);
    }
    public static class MyLeafProtocolB_Request_API_Test extends MyLeafProtocolB_Request_API {
        MyLeafProtocolB_Request_API_Test(StringBuilderProtocolMessage protocol) {
            super(protocol, true);
        }
    }
    /**
    * Argument: Leaf
    */
    public Leaf getLeaf() {
        return new Leaf(parent, protocol);
    }
    public static class Leaf extends AbstractDecoratedArgument {
        public static final String Leaf_ArgName = "Leaf";
        private final MyLeafProtocolB_Request_API parent;
        Leaf(MyLeafProtocolB_Request_API parent, IProtocolMessage protocol, int...indexes) {
            super(protocol, "Leaf", indexes);
            this.parent = parent;
        }
        public int getBitValue() {
            return _getBitValue(indexes);
        }
        public MyLeafProtocolB_Request_API setBitValue(int value) {
            _setBitValue(value, indexes);
            return parent;
        }
        public int getValue() {
            return _getValue(indexes);
        }
        public MyLeafProtocolB_Request_API setValue(int value) {
            _setValue(value + "", indexes);
            return parent;
        }
        public Quantity getRealQuantity() {
            return _getRealQuantity(indexes);
        }
        public MyLeafProtocolB_Request_API setRealQuantity(Quantity value) {
            _setRealQuantity(value, indexes);
            return parent;
        }
        public double getRealValue() {
            return _getRealValue(indexes);
        }
        public MyLeafProtocolB_Request_API setRealValue(double value) {
            _setRealValue(value, indexes);
            return parent;
        }
    }
    public <T extends APICommand<MyLeafProtocolB_Request_API>> MyLeafProtocolB_Request_API execute(T...commands) {
        for (APICommand<MyLeafProtocolB_Request_API> c: commands) {
            c.execute(this);
        }
        return this;
    }
}
