package org.jprotocol.example.api;
import org.jprotocol.framework.api.*;
import org.jprotocol.framework.dsl.*;
import java.util.Iterator;
import org.jprotocol.framework.test.ITestable;
/**
* MyLeafProtocolA Response
* @note This class is generated by DefaultAPIGenerator.groovy
*/
@SuppressWarnings("all")
public class MyLeafProtocolA_Response_API extends AbstractDecoratedProtocolMessage {
    public static final String NAME = "MyLeafProtocolA Response";
    private final MyLeafProtocolA_Response_API parent;
    public MyLeafProtocolA_Response_API(IProtocolLayoutType type) {
        this(new ProtocolMessage(type, false));
    }
    public MyLeafProtocolA_Response_API(IProtocolMessage protocol) {
        this(protocol, false);
    }
    private MyLeafProtocolA_Response_API(IProtocolMessage protocol, boolean strBuilder) {
        super(protocol, strBuilder);
        this.parent = this;
    }
    static MyLeafProtocolA_Response_API_Test createTest(StringBuilderProtocolMessage protocol) {
        return new MyLeafProtocolA_Response_API_Test(protocol);
    }
    public static class MyLeafProtocolA_Response_API_Test extends MyLeafProtocolA_Response_API {
        MyLeafProtocolA_Response_API_Test(StringBuilderProtocolMessage protocol) {
            super(protocol, true);
        }
    }
    public <T extends APICommand<MyLeafProtocolA_Response_API>> MyLeafProtocolA_Response_API execute(T...commands) {
        for (APICommand<MyLeafProtocolA_Response_API> c: commands) {
            c.execute(this);
        }
        return this;
    }
}
