package org.jprotocol.example.api;
import org.jprotocol.framework.api.*;
import org.jprotocol.framework.dsl.*;
import java.util.Iterator;
import org.jprotocol.framework.test.ITestable;
/**
* MyMiddleProtocolA Response
* @note This class is generated by DefaultAPIGenerator.groovy
*/
@SuppressWarnings("all")
public class MyMiddleProtocolA_Response_API extends AbstractDecoratedProtocolMessage {
    public static final String NAME = "MyMiddleProtocolA Response";
    private final MyMiddleProtocolA_Response_API parent;
    public MyMiddleProtocolA_Response_API(IProtocolLayoutType type) {
        this(new ProtocolMessage(type, false));
    }
    public MyMiddleProtocolA_Response_API(IProtocolMessage protocol) {
        this(protocol, false);
    }
    private MyMiddleProtocolA_Response_API(IProtocolMessage protocol, boolean strBuilder) {
        super(protocol, strBuilder);
        this.parent = this;
    }
    static MyMiddleProtocolA_Response_API_Test createTest(StringBuilderProtocolMessage protocol) {
        return new MyMiddleProtocolA_Response_API_Test(protocol);
    }
    public static class MyMiddleProtocolA_Response_API_Test extends MyMiddleProtocolA_Response_API {
        MyMiddleProtocolA_Response_API_Test(StringBuilderProtocolMessage protocol) {
            super(protocol, true);
        }
    }
}
