package org.jprotocol.example.api;
import org.jprotocol.framework.api.*;
import org.jprotocol.framework.dsl.*;
import java.util.Iterator;
import org.jprotocol.framework.test.ITestable;
/**
* MyMiddleProtocolB Response
* @note This class is generated by DefaultAPIGenerator.groovy
*/
@SuppressWarnings("all")
public class MyMiddleProtocolB_Response_API extends AbstractDecoratedProtocolMessage {
    public static final String NAME = "MyMiddleProtocolB Response";
    private final MyMiddleProtocolB_Response_API parent;
    public MyMiddleProtocolB_Response_API(IProtocolLayoutType type) {
        this(new ProtocolMessage(type, false));
    }
    public MyMiddleProtocolB_Response_API(IProtocolMessage protocol) {
        this(protocol, false);
    }
    private MyMiddleProtocolB_Response_API(IProtocolMessage protocol, boolean strBuilder) {
        super(protocol, strBuilder);
        this.parent = this;
    }
    static MyMiddleProtocolB_Response_API_Test createTest(StringBuilderProtocolMessage protocol) {
        return new MyMiddleProtocolB_Response_API_Test(protocol);
    }
    public static class MyMiddleProtocolB_Response_API_Test extends MyMiddleProtocolB_Response_API {
        MyMiddleProtocolB_Response_API_Test(StringBuilderProtocolMessage protocol) {
            super(protocol, true);
        }
    }
}
