package org.jprotocol.example.api;
import org.jprotocol.framework.api.*;
import org.jprotocol.framework.dsl.*;
import java.util.Iterator;
import org.jprotocol.framework.test.ITestable;
/**
* MyRootProtocol Response
* @note This class is generated by DefaultAPIGenerator.groovy
*/
@SuppressWarnings("all")
public class MyRootProtocol_Response_API extends AbstractDecoratedProtocolMessage {
    public static final String NAME = "MyRootProtocol Response";
    private final MyRootProtocol_Response_API parent;
    public MyRootProtocol_Response_API(IProtocolLayoutType type) {
        this(new ProtocolMessage(type, false));
    }
    public MyRootProtocol_Response_API(IProtocolMessage protocol) {
        this(protocol, false);
    }
    private MyRootProtocol_Response_API(IProtocolMessage protocol, boolean strBuilder) {
        super(protocol, strBuilder);
        this.parent = this;
    }
    static MyRootProtocol_Response_API_Test createTest(StringBuilderProtocolMessage protocol) {
        return new MyRootProtocol_Response_API_Test(protocol);
    }
    public static class MyRootProtocol_Response_API_Test extends MyRootProtocol_Response_API {
        MyRootProtocol_Response_API_Test(StringBuilderProtocolMessage protocol) {
            super(protocol, true);
        }
    }
}
