package org.jprotocol.example.api;
/**
* This class is generated by DefaultAPIFactoryGenerator.groovy
* @author eliasa01
*/
public class RequestAPIFactory {
    MyLeafProtocolA_Request_API MyLeafProtocolA_Request_API() {
        return MyLeafProtocolA_Request_API.createTest();
    }
    MyLeafProtocolB_Request_API MyLeafProtocolB_Request_API() {
        return MyLeafProtocolB_Request_API.createTest();
    }
    MyMiddleProtocolA_Request_API MyMiddleProtocolA_Request_API() {
        return MyMiddleProtocolA_Request_API.createTest();
    }
    MyMiddleProtocolB_Request_API MyMiddleProtocolB_Request_API() {
        return MyMiddleProtocolB_Request_API.createTest();
    }
    MyRootProtocol_Request_API MyRootProtocol_Request_API() {
        return MyRootProtocol_Request_API.createTest();
    }
}
